remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - README.md
  - JAVASCRIPT.md
  - REACTJS.md
  - LINKS.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
